//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.07.23 at 02:54:04 PM CEST 
//


package knife.maven.generated_slim_pom_4_0_0;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the knife.maven.generated_slim package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Project_QNAME = new QName("http://maven.apache.org/POM/4.0.0", "project");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: knife.maven.generated_slim
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Parent }
     * 
     */
    public Parent createParent() {
        return new Parent();
    }

    /**
     * Create an instance of {@link Model }
     * 
     */
    public Model createModel() {
        return new Model();
    }

    /**
     * Create an instance of {@link Dependency.Exclusions }
     * 
     */
    public Dependency.Exclusions createDependencyExclusions() {
        return new Dependency.Exclusions();
    }

    /**
     * Create an instance of {@link DependencyManagement }
     * 
     */
    public DependencyManagement createDependencyManagement() {
        return new DependencyManagement();
    }

    /**
     * Create an instance of {@link Dependency }
     * 
     */
    public Dependency createDependency() {
        return new Dependency();
    }

    /**
     * Create an instance of {@link Model.Dependencies }
     * 
     */
    public Model.Dependencies createModelDependencies() {
        return new Model.Dependencies();
    }

    /**
     * Create an instance of {@link Model.Properties }
     * 
     */
    public Model.Properties createModelProperties() {
        return new Model.Properties();
    }

    /**
     * Create an instance of {@link Exclusion }
     * 
     */
    public Exclusion createExclusion() {
        return new Exclusion();
    }

    /**
     * Create an instance of {@link Model.Modules }
     * 
     */
    public Model.Modules createModelModules() {
        return new Model.Modules();
    }

    /**
     * Create an instance of {@link DependencyManagement.Dependencies }
     * 
     */
    public DependencyManagement.Dependencies createDependencyManagementDependencies() {
        return new DependencyManagement.Dependencies();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Model }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://maven.apache.org/POM/4.0.0", name = "project")
    public JAXBElement<Model> createProject(Model value) {
        return new JAXBElement<Model>(_Project_QNAME, Model.class, null, value);
    }

}
